#ifndef _ENUMS_H_
#define _ENUMS_H_

enum OBJLIST {OBJ_BACKGROUND, OBJ_GROUNDTILE, OBJ_FILLERTILE, OBJ_ETC, OBJ_PLAYER, OBJ_ENEMY, OBJ_BULLET, OBJ_ITEM, OBJ_UI, OBJ_FONT, OBJ_Wind, H1, H2, H3, OBJ_END};

enum bulletType { DEFAULT, FIRE, SHRINK, METAL, GOLD, GHOST };

#endif